### ISSUE TITLE
tFinance dataset is missing

### ISSUE THREAD

**Issue by xwasco** [yixinliu233/ARC#1]
Dear all, thanks for your work!

Could you provide us the tFinance.mat file?

Thanks

Seba

**Comment by Shiy-Li** [comment]
Thank you for your attention! 
tFinance.mat can't be uploaded to GitHub due to size limitations, we've provided a link to that data via [Google Drive](https://drive.google.com/file/d/1mvqGlqS1hvAGj9TkA0vIHjNDX3291Ugx/view?usp=sharing).
